export const siteConfig = {
  name: "Matheus Liberato - AI Developer & Web Consultant",
  authorName: "Matheus Liberato",
  username: "Matheus-Liberato-dev",
  description:
    "Matheus Liberato - AI Developer & Web Consultant based in Sydney. I help individuals and small businesses build software, websites, and learn to use AI.",
  url: "https://matheustudio.com.au",
  links: {
    twitter: "https://twitter.com/matheustudio",
    github: "https://github.com/Matheus-Liberato-dev",
    templateRepo: "https://github.com/Matheus-Liberato-dev/matheus-studio",
  },
  ogImage: "/og-image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Matheus Liberato",
    "AI Developer",
    "Web Consultant",
    "Web Developer",
    "Software Engineer",
    "Full Stack Developer",
    "Next.js Developer",
    "React Developer",
    "Python Developer",
    "Large Language Models",
    "LLM",
    "AI Applications",
    "Web Development",
    "Sydney",
    "Australia",
    "Freelance Developer",
    "Small Business Websites",
    "Claude AI",
  ],
};
